name: ci-cd
on:
  workflow_dispatch:
  # push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      - name: Install frontend dependencies
        run: npm install --force
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Install backend dependencies
        run: npm install --force
        working-directory: backend

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/, frontend/dist/"
          target: "/home/ubuntu/app"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app/backend

            # Create .env file
            cat << EOF > .env
            MONGO_URI=mongodb+srv://${{ secrets.MONGO_USER }}:${{ secrets.MANGO_PASSWORD }}@cluster0.lmzuqki.mongodb.net/real-estate-platform?appName=Cluster0
            FRONTEND_URL=http://${{ secrets.EC2_HOST }}
            JWT_EXPIRE=30d
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            NODE_ENV=production
            PORT=5000
            EOF

            # Install dependencies
            npm install --force

            # Restart app with PM2
            pm2 restart propconnect || pm2 start server.js --name propconnect
            pm2 save